language: python

matrix:
    include:
        - python: 3.8

services:
    - postgresql
    - memcached

before_install:
    - sudo apt install -y libmemcached-dev
    - git config --global url."https://github.com/".insteadOf "git@github.com:"
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - source "$HOME/miniconda/etc/profile.d/conda.sh"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a
    - pip install -U pip

install:
    - conda env create -f environment.yml
    - conda activate ermaket

before_script:
    - psql -c 'create database ermaket;' -U postgres
    - psql -c "CREATE USER ermaket WITH PASSWORD 'ermaket777';" -U postgres
    - psql -c 'GRANT ALL PRIVILEGES ON DATABASE "ermaket" to ermaket;' -U postgres
    - psql -c 'ALTER USER ermaket WITH CREATEROLE;' -U postgres

script:
    - cd ermaket && export PYTHONPATH=$PYTHONPATH:$(pwd) && python -m pytest --timeout=30 --instafail --cov-config=.coveragerc --cov=. --log-cli-level=INFO

after_success:
    bash <(curl -s https://codecov.io/bash)
