coverage:
  range: 80..100
  round: down
  precision: 2
  ignore:
    - "./src/api/generation/templates/*"
    - './src/tests/dummy_scripts/*'

  status:
    project:
      default:
        enabled: yes
        target: 90
        threshold: null
    patch:
      default:
        enabled: no
