coverage:
  range: 80..100
  round: down
  precision: 2

  status:
    project:
      default:
        enabled: yes
        target: 90
        threshold: null
        if_not_found:
        if_ci_failed:
    patch:
      default:
        enabled: no
