coverage:
  range: 80..100
  round: down
  precision: 2

  status:
    project:
      default:
        enabled: yes
        target: 90
        threshold: null
    patch:
      default:
        enabled: no
