name: ermaket
channels:
  - defaults
dependencies:
  - flask
  - gunicorn
  - python=3.8.0
  - python-language-server
  - pytest
  - pytest-cov
  - pip
  - numpy
  - pip:
    - sqlalchemy
    - psycopg2-binary
    - mixer
    - tqdm
    - marshmallow_sqlalchemy
    - sqlalchemy_json_querybuilder
    - stringcase
    - flask_debugtoolbar
    - simplejson
    - pylama
    - neovim
    - pudb
    - ipdb
    - repr
    - bs4
    - lxml
    - pytest-pudb
    - python-dotenv
    - flask-login
    - prettierfier
    - deepmerge
    - git+https://github.com/SqrtMinusOne/flask-session.git
    - flask_cors
    - boltons
