# This file was generated automatically and will be overwritten
# with next generation. Make changes with caution

import sqlalchemy as sa

from .base import Base

__all__ = ['Er1Item']


class Er1Item(Base):
    __tablename__ = 'item'
    __table_args__ = ({'schema': 'er1'})

    id = sa.Column(
        sa.BigInteger(),
        primary_key=True,
        nullable=False,
        unique=True,
        autoincrement=True
    )
    name = sa.Column(
        sa.String(256),
        primary_key=False,
        nullable=False,
        unique=False,
        autoincrement=False
    )
    status = sa.Column(
        sa.Enum('Complete', 'Not complete', name='status'),
        primary_key=False,
        nullable=False,
        unique=False,
        autoincrement=False
    )

    subtask_name = sa.Column(
        sa.String(256),
        sa.ForeignKey(
            'er1.subtask.name', ondelete='cascade', onupdate='cascade'
        ),
        primary_key=False,
        unique=False
    )

    contains_subtask = sa.orm.relationship(
        'Er1Subtask',
        back_populates='item_contains',
        foreign_keys=[subtask_name]
    )

    def check_not_empty(self):
        """An autogenerated method.
        Call this after creation or update to check mandatory relationships.
        Returns False if at least one mandary relationship is invalid
        """
        return all([len(getattr(self, rel_name)) > 0 for rel_name in ()])

    def check_not_last(self):
        """An autogenerated method.
        Call this before deleting the object to check mandatory relationships.
        Returns False if at least one mandary relationship will become invalid.
        """
        return all([len(getattr(self, rel_name)) > 1 for rel_name in ()])
