# This file was generated automatically and will be overwritten
# with next generation. Make changes with caution

import sqlalchemy as sa

from .base import Base

__all__ = ['Er1Attachment']


class Er1Attachment(Base):
    __tablename__ = 'attachment'
    __table_args__ = ({'schema': 'er1'})

    id = sa.Column(
        sa.BigInteger(),
        primary_key=True,
        nullable=False,
        unique=True,
        autoincrement=True
    )
    contents = sa.Column(
        sa.Text(),
        primary_key=False,
        nullable=False,
        unique=False,
        autoincrement=False
    )

    task_id = sa.Column(
        sa.BigInteger(),
        sa.ForeignKey('er1.task.id', ondelete='cascade', onupdate='cascade'),
        primary_key=False,
        unique=False
    )

    is_attached_task = sa.orm.relationship(
        'Er1Task',
        back_populates='attachment_is_attached',
        foreign_keys=[task_id]
    )

    def check_not_empty(self):
        """An autogenerated method.
        Call this after creation or update to check mandatory relationships.
        Returns False if at least one mandary relationship is invalid
        """
        return all([len(getattr(self, rel_name)) > 0 for rel_name in ()])

    def check_not_last(self):
        """An autogenerated method.
        Call this before deleting the object to check mandatory relationships.
        Returns False if at least one mandary relationship will become invalid.
        """
        return all([len(getattr(self, rel_name)) > 1 for rel_name in ()])
